# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

from . import visitor as visitor
from ._types import ReferenceLike as ReferenceLike
from .formualizer_py import *
from .formualizer_py import EXCEL_ERROR_TOKENS as EXCEL_ERROR_TOKENS
from .formualizer_py import EvaluationConfig, WorkbookConfig
from .formualizer_py import excel_token_for_kind as excel_token_for_kind

__all__ = [
    "ASTNode",
    "Cell",
    "CellRef",
    "CellSnapshot",
    "CellSnapshotReport",
    "CycleTelemetry",
    "Dependent",
    "DependentsReport",
    "EvaluationConfig",
    "EvaluationPlan",
    "ExcelError",
    "FormulaDialect",
    "LayerInfo",
    "LinkDisposition",
    "LiteralValue",
    "NameResolution",
    "NameResolutionKind",
    "NamedRangeRef",
    "OmittedCount",
    "OmittedCountKind",
    "Parser",
    "Precedent",
    "PrecedentReport",
    "Provenance",
    "RangeAddress",
    "RangePage",
    "RangeRef",
    "RefWalker",
    "ReferenceKind",
    "SemanticReference",
    "Sheet",
    "SheetPortSession",
    "SpillRole",
    "SpillRoleKind",
    "Staleness",
    "StateStamp",
    "TableRef",
    "Token",
    "TokenSubType",
    "TokenType",
    "Tokenizer",
    "TokenizerIter",
    "TraceDirection",
    "TraceGraph",
    "TraceLink",
    "TraceLinkKind",
    "TraceLinkKindType",
    "TraceLinkTarget",
    "TraceNode",
    "TraceNodes",
    "TraceNodesIter",
    "TruncationReport",
    "UnknownRef",
    "Workbook",
    "WorkbookConfig",
    "WorkbookMode",
    "XlsxPathSource",
    "excel_token_for_kind",
    "load_workbook",
    "load_workbook_bytes",
    "parse",
    "parse_formula",
    "recalculate_file",
    "recalculate_xlsx_bytes",
    "recalculate_xlsx_file",
    "tokenize",
    "EXCEL_ERROR_TOKENS",
    "DependencyStateUnavailableError",
    "ExcelEvaluationError",
    "FormualizerHostError",
    "InspectionError",
    "InspectionResourceExhaustedError",
    "InspectionRevisionMismatchError",
    "InvalidInspectionAddressError",
    "InvalidInspectionOptionsError",
    "ParserError",
    "SheetNotFoundError",
    "PyFormulaDialect",
    "PyRefWalker",
    "PyToken",
    "PyTokenSubType",
    "PyTokenType",
    "PyTokenizer",
    "PyTokenizerIter",
    "SheetPortConstraintError",
    "SheetPortError",
    "SheetPortManifestError",
    "SheetPortWorkbookError",
    "TokenizerError",
    "ReferenceLike",
    "visitor",
    "QUALIFIED_WORKBOOK_SEED",
    "qualified_config",
    "qualified_eval_config",
    "set_qualified_clock",
]

# Provenance of the compiled extension (GOD-230): `commit` is the 40-hex fork
# commit, or None; `dirty` is a bool, or None. Never fabricated, and carries no
# timestamp so builds stay reproducible.
__build__: dict[builtins.str, typing.Any]

# GOD-230 qualification helpers, implemented in formualizer/__init__.py.
QUALIFIED_WORKBOOK_SEED: builtins.int

def qualified_eval_config(
    *,
    workbook_seed: builtins.int = ...,
    cycle_detection: builtins.str = ...,
) -> EvaluationConfig:
    ...

def qualified_config(
    *,
    workbook_seed: builtins.int = ...,
    cycle_detection: builtins.str = ...,
    eval_config: EvaluationConfig | None = ...,
) -> WorkbookConfig:
    ...

def set_qualified_clock(
    target: typing.Any,
    clock_seconds: builtins.float,
    utc_offset_seconds: builtins.int,
) -> None:
    ...
